=== rhoadsj/FhirBallots/tracker.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="trackerItems">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="item"/>
      </xs:sequence>
      <xs:attribute name="lastChange" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="item">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="ballot"/>
        <xs:element maxOccurs="unbounded" ref="resources"/>
        <xs:element maxOccurs="unbounded" ref="hTMLPages"/>
        <xs:element maxOccurs="unbounded" ref="reviewingWorkGroup"/>
        <xs:element minOccurs="0" ref="details"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="resolution"/>
        <xs:element minOccurs="0" ref="dup"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="comment"/>
        <xs:element maxOccurs="unbounded" ref="change"/>
      </xs:sequence>
      <xs:attribute name="ballot-weight" type="xs:NCName"/>
      <xs:attribute name="ballotResolution"/>
      <xs:attribute name="category" use="required" type="xs:NCName"/>
      <xs:attribute name="changeType"/>
      <xs:attribute name="closed" use="required"/>
      <xs:attribute name="group"/>
      <xs:attribute name="in-Person" type="xs:NCName"/>
      <xs:attribute name="modified" use="required"/>
      <xs:attribute name="modifiedEmail" use="required"/>
      <xs:attribute name="modifiedName" use="required"/>
      <xs:attribute name="moverSeconderFor-Against-Abstain"/>
      <xs:attribute name="number" use="required" type="xs:integer"/>
      <xs:attribute name="opened" use="required"/>
      <xs:attribute name="pre-applied" type="xs:NCName"/>
      <xs:attribute name="realSubmitter"/>
      <xs:attribute name="resolutionDate"/>
      <xs:attribute name="retractWithdraw" type="xs:NCName"/>
      <xs:attribute name="schedule" type="xs:NCName"/>
      <xs:attribute name="sectionnumber"/>
      <xs:attribute name="specification" use="required"/>
      <xs:attribute name="status" use="required"/>
      <xs:attribute name="submittedEmail" use="required"/>
      <xs:attribute name="submittedName" use="required"/>
      <xs:attribute name="summary" use="required"/>
      <xs:attribute name="targetrelease" type="xs:NCName"/>
      <xs:attribute name="url"/>
      <xs:attribute name="waitingforInpute-mails"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ballot" type="xs:string"/>
  <xs:element name="resources" type="xs:string"/>
  <xs:element name="hTMLPages" type="xs:string"/>
  <xs:element name="reviewingWorkGroup" type="xs:string"/>
  <xs:element name="details">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="a"/>
        <xs:element ref="p"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="resolution">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="a"/>
        <xs:element ref="em"/>
        <xs:element ref="p"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="dup" type="xs:NMTOKEN"/>
  <xs:element name="comment">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="a"/>
        <xs:element ref="br"/>
        <xs:element ref="img"/>
        <xs:element ref="p"/>
        <xs:element ref="strong"/>
      </xs:choice>
      <xs:attribute name="authorEmail" use="required"/>
      <xs:attribute name="authorName" use="required"/>
      <xs:attribute name="date" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="change">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="element"/>
      </xs:sequence>
      <xs:attribute name="authorEmail" use="required"/>
      <xs:attribute name="authorName" use="required"/>
      <xs:attribute name="date" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="element">
    <xs:complexType>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
      <xs:attribute name="new" use="required"/>
      <xs:attribute name="old" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="p">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="a"/>
        <xs:element ref="br"/>
        <xs:element ref="em"/>
        <xs:element ref="img"/>
        <xs:element ref="p"/>
        <xs:element ref="s"/>
        <xs:element ref="strong"/>
        <xs:element ref="u"/>
        <xs:element ref="script"/>
        <xs:element ref="span"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="script">
    <xs:complexType/>
  </xs:element>
  <xs:element name="span">
    <xs:complexType mixed="true">
      <xs:attribute name="style" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="a">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="br"/>
        <xs:element ref="em"/>
        <xs:element ref="img"/>
        <xs:element ref="strong"/>
        <xs:element ref="u"/>
      </xs:choice>
      <xs:attribute name="href" type="xs:anyURI"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="em">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="a"/>
        <xs:element ref="br"/>
        <xs:element ref="strong"/>
        <xs:element ref="u"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="br">
    <xs:complexType/>
  </xs:element>
  <xs:element name="strong">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="a"/>
        <xs:element ref="br"/>
        <xs:element ref="em"/>
        <xs:element ref="img"/>
        <xs:element ref="s"/>
        <xs:element ref="u"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="img">
    <xs:complexType>
      <xs:attribute name="alt" use="required"/>
      <xs:attribute name="src" use="required" type="xs:anyURI"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="s">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="a"/>
        <xs:element ref="strong"/>
        <xs:element ref="u"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="u">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="a"/>
        <xs:element ref="em"/>
        <xs:element ref="strong"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== rhoadsj/FhirBallots/data/fern.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<trackerItems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="../schemas/tracker.xsd" lastChange="2019-11-10 15:16:07.413463+00">
   <item number="18273" summary="Provide Guidance on how to use the artifacts"
      opened="2018-09-24 22:05:46+00" priority="3" closed="2018-10-31 14:56:31+00"
      submittedName="Eric Haas" submittedEmail="ehaas@healthedatainc.com" submittedId="emhaas"
      modified="2019-01-28 15:51:48+00" modifiedName="John Rhoads"
      modifiedEmail="john.rhoads@philips.com" modifiedId="jrhoads" realSubmitter="Eric Haas"
      specification="Point of Care Devices" category="Enhancement" ballot-weight="Negative-Major"
      in-Person="No" group="Follow-Up" status="Resolved - Change required"
      ballotResolution="Persuasive" resolutionDate="Oct 31 2018" changeType="Non-substantive"
      moverSeconderFor-Against-Abstain="Karl / Reinhold: 7-0-1" pre-applied="No"
      targetrelease="DSTURelease2" assigneeName="John Rhoads"
      assigneeEmail="john.rhoads@philips.com" assigneeId="jrhoads">
      <details><p>This IG provides FHIR profiles without any guidance how to use them.  Provide
            Guidance on how to use these artifacts allong with inline example.... perhaps by walking
            through a use case or two.</p><p> </p></details>
      <ballot>2018-Sep PoCD</ballot>
      <resources>None</resources>
      <hTMLPages>(profiles)</hTMLPages>
      <reviewingWorkGroup>IG Project</reviewingWorkGroup>
      <resolution><p>Agree. Material will be added in next ballot. See comments.</p></resolution>
      <tracker_item_id>18273</tracker_item_id>


      <close_date>2018-10-31 14:56:31+00</close_date>




      <last_modified_by>489</last_modified_by>
      <assignee>489</assignee>
      <comment date="2018-09-24 22:09:50.507117+00" authorName="Eric Haas"
         authorEmail="ehaas@healthedatainc.com" authorId="emhaas"><p>The IG stated
            purpose:</p><p>"This Implementation Guide defines the use of FHIR resources to convey
            measurements and supporting data from acute care point-of-care medical devices (PoCD) to
            receiving systems for electronic medical records, clinical decision support, and medical
            data archiving for aggregate quality measurement and research purposes.
            "</p><p> </p><p>Is impossible to achieve without appropriate guidance.</p></comment>
      <comment date="2018-10-29 15:23:54.511717+00" authorName="John Rhoads"
         authorEmail="john.rhoads@philips.com" authorId="jrhoads"><p>This is true. We will invest
            more time in filling in these gaps with guidance section, use case discussions, and more
            complete examples.</p></comment>
      <change date="2018-09-24 22:05:46.051979+00" authorName="Eric Haas"
         authorEmail="ehaas@healthedatainc.com" authorId="emhaas">
         <element name="_created_" old="" new="Provide Guidance on how to use the artifacts"/>
      </change>
      <change date="2018-09-24 22:09:50.507117+00" authorName="Eric Haas"
         authorEmail="ehaas@healthedatainc.com" authorId="emhaas">
         <element name="resolution" old="-" new=""/>
      </change>
      <change date="2018-09-26 17:50:52.427679+00" authorName="Melva Peters"
         authorEmail="melva@jenakerconsulting.com" authorId="mpeters">
         <element name="hTMLPages" old="None" new="(profiles)"/>
         <element name="reviewingWorkGroup" old="None" new="IG Project"/>
      </change>
      <change date="2018-09-26 17:51:10.784967+00" authorName="Melva Peters"
         authorEmail="melva@jenakerconsulting.com" authorId="mpeters">
         <element name="status" old="Submitted" new="Triaged"/>
      </change>
      <change date="2018-10-29 15:07:47.686939+00" authorName="John Rhoads"
         authorEmail="john.rhoads@philips.com" authorId="jrhoads">
         <element name="group" old="None" new="Fit for teleconference"/>
         <element name="ballot" old="None" new="2018-Sep PoCD"/>
      </change>
      <change date="2018-10-31 14:56:31.284341+00" authorName="John Rhoads"
         authorEmail="john.rhoads@philips.com" authorId="jrhoads">
         <element name="waitingFor" old="Assignee(s)" new="None"/>
         <element name="group" old="Fit for teleconference" new="None"/>
         <element name="close_date" old="None" new="2018-10-31 10:56:31"/>
         <element name="pre-applied" old="None" new="No"/>
         <element name="status" old="Triaged" new="Resolved - Change required"/>
         <element name="status_id" old="1" new="0"/>
      </change>
      <change date="2018-10-31 15:01:39.088902+00" authorName="John Rhoads"
         authorEmail="john.rhoads@philips.com" authorId="jrhoads">
         <element name="moverSeconderFor-Against-Abstain" old="" new="Karl / Reinhold: 7-0-1"/>
         <element name="resolutionDate" old="" new="Oct 31 2018"/>
         <element name="changeType" old="None" new="Non-substantive"/>
         <element name="ballotResolution" old="None" new="Persuasive"/>
      </change>
      <change date="2018-10-31 15:04:46.590057+00" authorName="John Rhoads"
         authorEmail="john.rhoads@philips.com" authorId="jrhoads">
         <element name="targetrelease" old="2.0.6" new="DSTURelease2"/>
         <element name="group" old="None" new="Follow-Up"/>
      </change>
      <change date="2018-11-14 17:06:51.967155+00" authorName="John Rhoads"
         authorEmail="john.rhoads@philips.com" authorId="jrhoads">
         <element name="ballot-weight" old="None" new="Negative-Major"/>
         <element name="resolution" old="-"
            new="&lt;p&gt;Agree. Material will be added in next ballot. See comments.&lt;/p&gt;"/>
      </change>
      <change date="2019-01-28 15:51:47.953443+00" authorName="John Rhoads"
         authorEmail="john.rhoads@philips.com" authorId="jrhoads">
         <element name="assignee" old="None" new="John Rhoads"/>
         <element name="assignee" old="Nobody " new="Removed"/>
      </change>
   </item>
   <item number="18275" summary="terminology is not easily accessible"
      opened="2018-09-24 22:12:33+00" priority="3" closed="2018-10-31 15:00:17+00"
      submittedName="Eric Haas" submittedEmail="ehaas@healthedatainc.com" submittedId="emhaas"
      modified="2019-01-28 15:51:48+00" modifiedName="John Rhoads"
      modifiedEmail="john.rhoads@philips.com" modifiedId="jrhoads" realSubmitter="Eric Haas"
      specification="Point of Care Devices"
      url="http://hl7.org/fhir/uv/pocd/2018Sep/terminology.html" category="Enhancement"
      ballot-weight="Negative-Major" in-Person="No" group="Follow-Up"
      status="Resolved - Change required" ballotResolution="Persuasive" resolutionDate="Oct 31 2018"
      changeType="Non-substantive" moverSeconderFor-Against-Abstain="Karl / Reinhold: 7-0-1"
      pre-applied="No" targetrelease="DSTURelease2" assigneeName="John Rhoads"
      assigneeEmail="john.rhoads@philips.com" assigneeId="jrhoads">
      <details><p>The ISO/IEEE 11073-10101 Nomenclature standard (11073 MDC) provides a
            comprehensive terminology for device models according to the ISO/IEEE 11073-10201 Domain
            information model (DIM). It's the preferred code system for profiles in this
            implementation guide. Reference identifiers, terminology codes, and descriptions are
            available at the <a href="https://rtmms.nist.gov/rtmms/index.htm">Rosetta Terminology
               Mapping Management System</a> (RTMMS)..</p><p> </p><p>The link does not provide an
            easy entry point to the MDC codes nor can they be inspected through the FHIR
            valuesets.</p></details>
      <ballot>2018-Sep PoCD</ballot>
      <resources>None</resources>
      <hTMLPages>(profiles)</hTMLPages>
      <reviewingWorkGroup>IG Project</reviewingWorkGroup>
      <resolution><p>Agree. Work in progress for next ballot.</p></resolution>
      <tracker_item_id>18275</tracker_item_id>


      <close_date>2018-10-31 15:00:17+00</close_date>




      <last_modified_by>489</last_modified_by>
      <assignee>489</assignee>
      <comment date="2018-09-24 22:13:56.375564+00" authorName="Eric Haas"
         authorEmail="ehaas@healthedatainc.com" authorId="emhaas"><p>For broad adoption I think
            there needs to be low barrier to accessing the terminology.</p></comment>
      <comment date="2018-10-29 15:22:01.878009+00" authorName="John Rhoads"
         authorEmail="john.rhoads@philips.com" authorId="jrhoads"><p>Valid. Now a general
            introduction to the use of MDC codes in FHIR is available in the R4 specification.
            General lookup information on individual codes and downloads of information on the set
            of codes is available via the RTMMS website, and work is in progress on making these
            available in FHIR resource forms at the FHIR terminology servers when the status
            information is available from the RTMMS downloads.</p></comment>
      <change date="2018-09-24 22:12:33.427166+00" authorName="Eric Haas"
         authorEmail="ehaas@healthedatainc.com" authorId="emhaas">
         <element name="_created_" old="" new="terminology is not easily accessible"/>
      </change>
      <change date="2018-09-24 22:13:56.375564+00" authorName="Eric Haas"
         authorEmail="ehaas@healthedatainc.com" authorId="emhaas">
         <element name="resolution" old="-" new=""/>
         <element name="url"
            old="&lt;a href=&#34;http://hl7.org/fhir/uv/pocd/2018Sep/terminology.html&#34;&gt;http://hl7.org/fhir/uv/pocd/2018Sep/terminology.html&lt;/a&gt;"
            new="http://hl7.org/fhir/uv/pocd/2018Sep/terminology.html"/>
      </change>
      <change date="2018-09-26 17:50:52.427679+00" authorName="Melva Peters"
         authorEmail="melva@jenakerconsulting.com" authorId="mpeters">
         <element name="reviewingWorkGroup" old="None" new="IG Project"/>
